version: '3'

services:
  web:
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      RAILS_ENV: development
      BUNDLE_BIN: "/usr/src/app/vendor/.bundle/ruby/3.2.0/bin"
      BUNDLE_PATH: "/usr/src/app/vendor/.bundle/ruby/3.2.0"
      BUNDLE_APP_CONFIG: "/usr/src/app/.bundle"
    command: bundle exec rails server -b 0.0.0.0 -p 3000 -e development

  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  postgres-network:
    driver: bridge
  opensearch-net:
    driver: bridge
